[package]
name = "generic-image"
description = "a zero dependency library"
version = "0.8.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies]
png = "0.17.11"
